import { createApp } from "vue";
import App from "./App.vue";

// 开发阶段引入
import { SButton } from "../../packages/base/button/index";
import { SIcon } from "../../packages/base/icon/index";
import { SInput } from "../../packages/base/input/index";
import { SBadge } from "../../packages/base/badge/index";
import { STag } from "../../packages/base/tag/index";
import { STooltip } from "../../packages/base/tooltip/index";
import { SRipple } from "../../packages/base/ripple/index";
import { SLoading } from "../../packages/base/loading/index";
import { SCheckbox } from "../../packages/base/checkbox/index";
import { SCheckboxGroup } from "../../packages/base/checkbox-group/index";
import { SRadio } from "../../packages/base/radio/index";
import { SRadioGroup } from "../../packages/base/radio-group/index";
import { SSwitch } from "../../packages/base/switch/index";
import { STextarea } from "../../packages/base/textarea/index";
import { SSelect } from "../../packages/base/select/index";
import { SOption } from "../../packages/base/option/index";
import { SInputNumber } from "../../packages/base/input-number/index";
import { SSlider } from "../../packages/base/slider/index";
import { SLayout } from "../../packages/base/layout/index";
import { SBox } from "../../packages/base/box/index";
import { SDivider } from "../../packages/base/divider/index";
import { SSpace } from "../../packages/base/space/index";
import { SLink } from "../../packages/base/link/index";
import { SAlert } from "../../packages/base/alert/index";
import { SDialog } from "../../packages/base/dialog/index";
import { SMessage, showMessage } from "../../packages/base/message/index";
import { SNotification, showNotification } from "../../packages/base/notification/index";
import { SConfirmBox, showConfirmBox } from "../../packages/base/confirm-box/index";
import { STable } from "../../packages/base/table/index";
import { SCard } from "../../packages/base/card/index";
import { SImage } from "../../packages/base/image/index";
import { SAvatar } from "../../packages/base/avatar/index";
import { SProgress } from "../../packages/base/progress/index";
import { SEmpty } from "../../packages/base/empty/index";
import { SPagination } from "../../packages/base/pagination/index";
import { STabs } from "../../packages/base/tabs/index";
import { SDropdown } from "../../packages/base/dropdown/index";
import { SDropdownItem } from "../../packages/base/dropdown-item/index";
import { SBreadcrumb } from "../../packages/base/breadcrumb/index";
import { SBreadcrumbItem } from "../../packages/base/breadcrumb-item/index";
import { STabsItem } from "../../packages/base/tabs-item/index";
import { SSteps } from "../../packages/base/steps/index";
import { SForm } from "../../packages/base/form/index";
import { SFormItem } from "../../packages/base/form-item/index";
import { SStepsItem } from "../../packages/base/steps-item/index";
import { SDatePicker } from "../../packages/base/date-picker/index";
import { SUpload } from "../../packages/base/upload/index";
import { SCountDown } from "../../packages/base/count-down/index";
import { SBackTop } from "../../packages/base/back-top/index";
import { SWatermark } from "../../packages/base/watermark/index";
import { SInfiniteScrolling } from "../../packages/base/infinite-scrolling/index";

const app = createApp(App);

app.use(SButton as any);
app.use(SIcon as any);
app.use(SInput as any);
app.use(SBadge as any);
app.use(STag as any);
app.use(STooltip as any);
app.use(SRipple as any);
app.use(SLoading as any);
app.use(SCheckbox as any);
app.use(SCheckboxGroup as any);
app.use(SRadio as any);
app.use(SRadioGroup as any);
app.use(SSwitch as any);
app.use(STextarea as any);
app.use(SSelect as any);
app.use(SOption as any);
app.use(SInputNumber as any);
app.use(SSlider as any);
app.use(SLayout as any);
app.use(SBox as any);
app.use(SDivider as any);
app.use(SSpace as any);
app.use(SLink as any);
app.use(SAlert as any);
app.use(SDialog as any);
app.use(SMessage as any);
app.use(SNotification as any);
app.use(SConfirmBox as any);
app.use(STable as any);
app.use(SCard as any);
app.use(SImage as any);
app.use(SAvatar as any);
app.use(SProgress as any);
app.use(SEmpty as any);
app.use(SPagination as any);
app.use(STabs as any);
app.use(STabsItem as any);
app.use(SDropdown as any);
app.use(SDropdownItem as any);
app.use(SBreadcrumb as any);
app.use(SBreadcrumbItem as any);
app.use(SSteps as any);
app.use(SStepsItem as any);
app.use(SForm as any);
app.use(SFormItem as any);
app.use(SDatePicker as any);
app.use(SUpload as any);
app.use(SCountDown as any);
app.use(SBackTop as any);
app.use(SWatermark as any);
app.use(SInfiniteScrolling as any);
(app as any).showMessage = showMessage;
(app as any).showNotification = showNotification;
(app as any).showConfirmBox = showConfirmBox;

app.mount("#dev");
